albums/urls.py
from django.urls import path
from .views import create, AlbumDetailView,AlbumListView

app_name='albums'

urlpatterns =[
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view() , name='detail'),
    path('', AlbumListView.as_view() , name='list')
]

aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

albums/models.py
from django.db import models
from django.db.models import Sum
from AWS import create_folder

class AlbumManager(models.Manager):
    def create_by_aws(self, bucket, title, description):
        key = title.replace(' ','_').lower()
        key = create_folder(bucket,key)
        if key :
            return self.create(title=title, 
                               description=description, 
                               bucket=bucket, 
                               key=key)

# Create your models here.
class Album(models.Model):
    title = models.CharField(max_length=50,null=False, blank=False)
    description = models.TextField()
    bucket = models.CharField(max_length=100,null=False, blank=False)
    key = models.CharField(max_length=100,null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AlbumManager()

    def __str__(self) :
        return self.title
    
    @property
    def images(self):
        return self.image_set.all()

    @property
    def size(self):
        if self.images:   
            return self.images.aggregate(Sum('size'))['size__sum']
        else:
            return 0

albums/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields =['title','description']

    def __init__(self,*args,**kwargs):
        super(AlbumForm,self).__init__(*args,**kwargs)

        self.fields['title'].widget.attrs.update({
            'class':'form-control',
            'id':'title',
            'placeholder':'Title'
        })
        self.fields['description'].widget.attrs.update({
            'class':'form-control',
            'id':'description',
            'placeholder':'Description'
        })

albums/views.py
from django.shortcuts import render, redirect
from .forms import AlbumForm
from .models import Album
from images.forms import UploadFileForm
from django.views.generic import DetailView, ListView
from django.conf import settings

# Create your views here.

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self,*args, **kwargs) :
        context =  super().get_context_data(*args,**kwargs)

        context['title'] = self.get_object().title
        context['images'] = self.get_object().images
        context['form'] = UploadFileForm({
            'album_id': self.get_object().id
        })
        return context
    

def create(request):
    form = AlbumForm(request.POST or None)
    if request.method =='POST' and form.is_valid():
        # album = form.save()
        album = Album.objects.create_by_aws(settings.BUCKET,form.cleaned_data['title'],form.cleaned_data['description'])
        return redirect('albums:list')

class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self,*args, **kwargs) :
        context =  super().get_context_data(*args,**kwargs)

        context['title'] = 'Galeria'
        context['form'] = AlbumForm()
        return context

albums/templates/albums/snippets/modal.html
  <!-- Modal -->
  <div class="modal fade" id="newAlbum" tabindex="-1" aria-labelledby="newAlbumLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="newAlbumLabel">Nuevo Album</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <form action="{% url 'albums:create' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
              
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input class="btn btn-primary" type="submit" value="Create" />
                </div>
            </form>
        </div>
    </div>
  </div>