albums/urls.py
from django.urls import path
from .views import create, AlbumDetailView,AlbumListView

app_name='albums'

urlpatterns =[
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view() , name='detail'),
    path('', AlbumListView.as_view() , name='list')
]

aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

images/urls.py
from django.urls import path
from .views import create, update, show, delete, download, delete_many, download_many, search

app_name='images'

urlpatterns =[
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('show/<int:pk>/', show, name='show'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('download/<int:pk>/', download, name='download'),
    path('download/many', download_many, name='download_many'),
    path('delete/many', delete_many, name='delete_many'),
    path('search', search, name='search')
]

images/models.py
from django.db import models
from albums.models import Album

from AWS import rename_file, delete_mediafile

class ImageManager(models.Manager):
    def delete_by_aws(self, id):
        image = self.filter(id= id).first()
        if image and delete_mediafile(image.bucket, image.key):
            image.delete()
            return id

# Create your models here.
class Image(models.Model):
    key = models.CharField(max_length=100, null=False, blank=False)
    bucket = models.CharField(max_length=100, null=False, blank=False)
    name = models.CharField(max_length=50, null=False, blank=False)
    content_type = models.CharField(max_length=20, null=False, blank=False)
    size = models.IntegerField()
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = ImageManager()

    def __str__(self):
        return self.name

    @property
    def url(self):
        return f"https://{self.bucket}.s3.amazonaws.com/{self.key}"    
    
    @property
    def title(self):
        return self.name.split('.')[0]
    @property
    def extension(self):
        return self.name.split('.')[-1]
    
    def set_name(self, new_name):
        new_name = new_name + '.' + self.extension
        new_key = self.album.key + new_name

        if rename_file(self.bucket, new_key, self.key):
            self.key= new_key
            self.name = new_name
            self.save()

images/forms.py
from django import forms

class UploadFileForm(forms.Form):
    album_id = forms.CharField(required=True, widget=forms.HiddenInput())
    file = forms.FileField(required=True, label='Imagen',
                           widget=forms.FileInput(attrs={'accept':'image/*'}))

    def __init__(self, *args,**kwargs):
        super(UploadFileForm, self).__init__(*args,**kwargs)

        self.fields['file'].widget.attrs['class'] = 'form-control-file'

images/views.py
import json
import shutil
from pathlib import Path
from wsgiref.util import FileWrapper
from AWS import upload_image,delete_mediafile, get_mediafile_content, download_file
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template
from django.urls import reverse
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from .forms import UploadFileForm
from .models import Image, Album

@csrf_exempt
def search(request):
    if request.method == 'GET' and request.GET.get('q'):

        template = get_template('images/snippets/image.html')
        images =[
            template.render({
                'image': image
            })
            for image in Image.objects.filter(name__startswith=request.GET['q'])
        ]
        return JsonResponse({
            'success': True,
            'images': images
        })    

def download(request, pk):
    image = get_object_or_404(Image, pk= pk)
    content = get_mediafile_content(image.bucket, image.key)
    response = HttpResponse(content, content_type=image.content_type)
    response['Content-Disposition'] = f'attachment; filename={image.name}'
    return response 

def show(request, pk):

    image = get_object_or_404(Image, pk=pk)
    return JsonResponse({
        'id': image.id,
        'name': image.name,
        'delete_url': reverse('images:delete', kwargs={'pk':image.id})
    })

def update(request, pk):
    image = get_object_or_404(Image, pk=pk)

    if request.method == 'POST':
        new_name = request.POST.get('name','')
        image.set_name(new_name)

    return JsonResponse({
        'id':image.id,
        'name':image.title,
        'url':image.url
    })

# Create your views here.
def create(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST , request.FILES)
        if form.is_valid():
            file = form.cleaned_data['file']
            album = get_object_or_404(Album, id= form.cleaned_data['album_id'])

            key = album.key + file._name
            if upload_image(settings.BUCKET , key, file):


                image = Image.objects.create(
                    name = file._name,
                    content_type = file.content_type,
                    size = file.size,
                    bucket = settings.BUCKET,
                    key = key,
                    album = album
                )

            return redirect('albums:detail', album.id)
        
def delete(request, pk):
    image = get_object_or_404(Image, pk=pk)
    album = image.album
    Image.objects.delete_by_aws(image.id)
    return redirect('albums:detail', album.id)

@csrf_exempt
def delete_many(request):
    if request.method == 'POST':
        payload = json.loads(request.body)
        ids = payload.get('ids', [])

    return JsonResponse({
        'ids': [ Image.objects.delete_by_aws(id) for id in ids]
    })

def download_many(request):
    dir_path = 'tmp/images'
    Path(dir_path).mkdir(parents=True, exist_ok=True)

    for id in request.GET.get('ids','').split(','):
        image = Image.objects.filter(id=int(id)).first()
        if image:
            local_path = dir_path + '/' + image.name
            download_file(image.bucket, image.key, local_path)
    shutil.make_archive('tmp/images','zip', dir_path)        
    wrapper = FileWrapper(open('tmp/images.zip','rb'))
    response = HttpResponse(wrapper,content_type='application/zip')
    response['Content-Disposition'] = 'attachment; filename = "images.zip"'
    return response

images/templates/images/snippets/delete.html
  
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="deleteModalLabel">Eliminar Imagen</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ¿Desea eliminar <strong id="strong-name"></strong>?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <a href="" class="btn btn-danger" id="delete-modal-button">Eliminar</a>
        </div>
      </div>
    </div>
  </div>

images/templates/images/snippets/image.html
<tr class="row-image" image-id="{{ image.id }}" id="image-{{ image.id }}">
    <td><div class="form-check">
        <input type="checkbox" name="" class="form-check-input check-images" id="" image-id="{{ image.id }}">
      </div></td>
  <td>
    <input
      type="hidden"
      value="{{ image.url }}"
      id="image-preview-{{ image.id }}"
    />
    <div id="image-name-{{ image.id }}">{{ image.name }}</div>
    <form
      action="{% url 'images:update' image.pk %}"
      method="POST"
      class="image-form"
      image-id="{{ image.id }}"
    >
      {% csrf_token %}
      <input
        type="hidden"
        value="{{ image.title }}"
        class="form-control"
        id="image-input-name-{{ image.id }}"
        name="name"
      />
    </form>
  </td>
  <td>{{ image.created_at }}</td>
  <td>{{ image.size }}</td>
  <td>
    <div class="btn-group">
      <button
        type="button"
        class="btn btn-secondary dropdown-toggle"
        data-bs-toggle="dropdown"
      ></button>
      <div class="dropdown-menu">
        <a
          href=" {{ image.url }} "
          target="_blank"
          class="dropdown-item"
          >Vista previa</a
        >
        <a
          href=""
          class="dropdown-item image-edit"
          image-id="{{ image.id }}"
          >Editar nombre</a
        >
        <a href="{% url 'images:download' image.id %}" class="dropdown-item">Descarga</a>
        <div class="dropdown-divider"></div>
        <a
          href="{% url 'images:show' image.id %}"
          class="dropdown-item"
          data-bs-toggle="modal"
          data-bs-target="#deleteModal"
          >Eliminar</a
        >
      </div>
    </div>
  </td>
</tr>

images/templates/images/snippets/modal.html
<!-- Modal -->
<div class="modal fade" id="newImage" tabindex="-1" aria-labelledby="newAlbumLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="newAlbumLabel">Nueva Imagen</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
            <form action="{% url 'images:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    {% for field in form %}
                        <div class="form-group">
                            {{ field }}
                        </div>
                    {% endfor %}
              
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input class="btn btn-primary" type="submit" value="Subir" />
                </div>
            </form>
        </div>
    </div>
  </div>