albums/urls.py
from django.urls import path
from .views import create, AlbumDetailView,AlbumListView

app_name='albums'

urlpatterns =[
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view() , name='detail'),
    path('', AlbumListView.as_view() , name='list')
]

aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls')),
    path('images/', include('images.urls')),
]

images/urls.py
from django.urls import path
from .views import create, update, show, delete, download, delete_many, download_many, search

app_name='images'

urlpatterns =[
    path('create/', create, name='create'),
    path('update/<int:pk>/', update, name='update'),
    path('show/<int:pk>/', show, name='show'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('download/<int:pk>/', download, name='download'),
    path('download/many', download_many, name='download_many'),
    path('delete/many', delete_many, name='delete_many'),
    path('search', search, name='search')
]

albums/models.py
from django.db import models
from django.db.models import Sum
from AWS import create_folder

class AlbumManager(models.Manager):
    def create_by_aws(self, bucket, title, description):
        key = title.replace(' ','_').lower()
        key = create_folder(bucket,key)
        if key :
            return self.create(title=title, 
                               description=description, 
                               bucket=bucket, 
                               key=key)

# Create your models here.
class Album(models.Model):
    title = models.CharField(max_length=50,null=False, blank=False)
    description = models.TextField()
    bucket = models.CharField(max_length=100,null=False, blank=False)
    key = models.CharField(max_length=100,null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AlbumManager()

    def __str__(self) :
        return self.title
    
    @property
    def images(self):
        return self.image_set.all()

    @property
    def size(self):
        if self.images:   
            return self.images.aggregate(Sum('size'))['size__sum']
        else:
            return 0

albums/forms.py
from django.forms import ModelForm
from .models import Album

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields =['title','description']

    def __init__(self,*args,**kwargs):
        super(AlbumForm,self).__init__(*args,**kwargs)

        self.fields['title'].widget.attrs.update({
            'class':'form-control',
            'id':'title',
            'placeholder':'Title'
        })
        self.fields['description'].widget.attrs.update({
            'class':'form-control',
            'id':'description',
            'placeholder':'Description'
        })

albums/views.py
from django.shortcuts import render, redirect
from .forms import AlbumForm
from .models import Album
from images.forms import UploadFileForm
from django.views.generic import DetailView, ListView
from django.conf import settings

# Create your views here.

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self,*args, **kwargs) :
        context =  super().get_context_data(*args,**kwargs)

        context['title'] = self.get_object().title
        context['images'] = self.get_object().images
        context['form'] = UploadFileForm({
            'album_id': self.get_object().id
        })
        return context
    

def create(request):
    form = AlbumForm(request.POST or None)
    if request.method =='POST' and form.is_valid():
        # album = form.save()
        album = Album.objects.create_by_aws(settings.BUCKET,form.cleaned_data['title'],form.cleaned_data['description'])
        return redirect('albums:list')

class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self,*args, **kwargs) :
        context =  super().get_context_data(*args,**kwargs)

        context['title'] = 'Galeria'
        context['form'] = AlbumForm()
        return context

albums/templates/albums/detail.html
{% extends 'base/index.html' %} {% block style %}
<style>
  .row-image {
    cursor: pointer;
  }
</style>
{% endblock %} {% block content %} 
{% include 'images/snippets/modal.html' %} 
{% include 'images/snippets/delete.html' %}

<div class="row mt-4">
    <div class="col">
        <form action="{% url 'images:search' %}" id="image-search">
            <input type="text" name="q" class="form-control" placeholder="Escriba un prefijo ... " id="">
        </form>
    </div>
</div>

<div class="row mt-2">
  <div class="col">
    <h4><a href="{% url 'albums:list' %}">Galería/</a> {{ object }}</h4>
  </div>
</div>
<hr />
<div class="row">
  <div class="col">
      <button
        type="button"
        class="btn btn-secondary"
        data-bs-toggle="modal"
        data-bs-target="#newImage"
      >
        Nueva Imagen
      </button>
      <a
        href="{% url 'images:download_many' %}"
        class="btn btn-info disabled"
        id="download-images"
      >
        Descargar
      </a>
      <a
        href="{% url 'images:delete_many' %}"
        class="btn btn-danger disabled"
        id="delete-images"
      >
        Eliminar
      </a>
</div>
</div>

<div class="row mt-3">
  <div class="col-8">
    <table class="table">
      <thead>
        <tr>
          <td><div class="form-check">
            <input type="checkbox" name="" class="form-check-input" id="check-all-images">
          </div></td>
          <th>Nombre</th>
          <th>Fecha de Creación</th>
          <th>Size</th>
          <th></th>
        </tr>
      </thead>
      <tbody id="table-images">
        {% for image in images %}
            {% include 'images/snippets/image.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-4">
    <img src="" alt="" width="300" height="300" id="image-preview" />
  </div>
</div>
{% endblock %} {% block javascript %}
<script>
    const imagePreview = document.getElementById("image-preview");
    const imageDefault = "https://cfimagenesproject.s3.amazonaws.com/vacio.png";
    const checkAllImages = document.getElementById('check-all-images')
    const downloadImages = document.getElementById('download-images')
    const deleteImages = document.getElementById('delete-images')
    const imageSearch = document.getElementById('image-search')

    function checkInputs(){
        let images = document.querySelectorAll('input.check-images[type="checkbox"]:checked')
        if (images.length>=2){
            downloadImages.classList.remove('disabled')
            deleteImages.classList.remove('disabled')
        }else{
            downloadImages.classList.add('disabled')
            deleteImages.classList.add('disabled')
        }
    }

    function getImagesSelected(){
        let ids = []
    let images = document.querySelectorAll('input.check-images[type="checkbox"]:checked')
        for(i=0; i<images.length; i++){
            let imageId = images[i].getAttribute('image-id')
            ids.push(imageId)
        }
    return ids
    }

    function selectRow(row) {
    let imageId = row.getAttribute("image-id");
    let input = document.getElementById("image-preview-" + imageId);
    imagePreview.src = input.value;

    document.querySelectorAll(".table-active").forEach((e) => {
      e.classList.remove("table-active");
    });

    row.classList.add("table-active");
  }

    function setDefaultImage() {
    let rows = document.getElementsByTagName("tr");
    if (rows.length >= 2) {
      selectRow(rows[1]);
    } else {
      imagePreview.src = imageDefault;
    }
  }

    function registerEvents(){
    
        document.querySelectorAll(".row-image").forEach((e) => {
    e.addEventListener("click", function (event) {
      selectRow(this);
    });
  });

        document.querySelectorAll(".image-edit").forEach((e) => {
    e.addEventListener("click", function (event) {
      event.preventDefault();
      let imageId = this.getAttribute("image-id");
      let input = document.getElementById("image-input-name-" + imageId);

      let div = document.getElementById("image-name-" + imageId);
      div.style.display = "none";
      input.setAttribute("type", "text");
    });
  });
    
        document.querySelectorAll(".image-form").forEach((e) => {
    e.addEventListener("submit", function (event) {
      event.preventDefault();

      fetch(this.action, {
        body: new FormData(this),
        method: "POST",
      })
        .then((response) => response.json())
        .then((data) => {
          let imageId = this.getAttribute("image-id");
          let input = document.getElementById("image-input-name-" + imageId);
          input.value = data.name;
          input.setAttribute("type", "hidden");
          let div = document.getElementById("image-name-" + imageId);
          div.innerHTML = data.name;
          div.style.display = "block";

          let preview = document.getElementById("image-preview-" + imageId);
          preview.value = data.url;
        });
    });
  });
        
        document.querySelectorAll('.check-images').forEach(e=>{
    e.addEventListener('change',function(event){
        checkInputs()
    })
  })
    }

  let deleteModal = document.getElementById("deleteModal");
  deleteModal.addEventListener("show.bs.modal", function (event) {

    let button = event.relatedTarget;
    fetch(button.href)
      .then((response) => response.json())
      .then(function (data) {
        let imageName = deleteModal.querySelector("#strong-name");
        imageName.textContent = data.name;
        let buttonId = deleteModal.querySelector('#delete-modal-button')
        buttonId.href = data.delete_url
      });
  });

  checkAllImages.addEventListener('change', function(e){
    document.querySelectorAll('.check-images').forEach(e=>{
        e.checked = this.checked
        checkInputs()
    })
  })
  deleteImages.addEventListener('click', function(event){
    event.preventDefault()
    let ids =getImagesSelected()
    
    fetch(this.href,{
        method:'POST',
        body : JSON.stringify({'ids': ids})
    })
    .then(response => response.json())
    .then(function(data){
        for(i=0;i<data.ids.length;i++){
            let imageId = data.ids[i]
            document.getElementById( "image-" + imageId).remove()
        }
        setDefaultImage();

    })
  })
  downloadImages.addEventListener('click', function(e){
    e.preventDefault()
    let ids =getImagesSelected()
    window.location.href = this.href + '?ids=' + ids
  })

  imageSearch.addEventListener('submit', function(e){
    e.preventDefault()
    fetch(this.action + '?q=' + this.q.value)
    .then(response => response.json())
    .then(data=>{
        let table = document.getElementById('table-images')
        table.innerHTML = data.images.toString().replaceAll(',','')   
        
        registerEvents();
        setDefaultImage();
    })
  })

  registerEvents();
  setDefaultImage();
</script>
{% endblock %}

albums/templates/albums/list.html
{% extends 'base/index.html ' %} {% block content %}
{% include 'albums/snippets/modal.html' %}
<div class="row mt-4">
    <div class="col-6">
      <h2>Galeria</h2>
    </div>

    <div class="col-6 text-right">
        <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#newAlbum">
            Nuevo Album
          </button>
    </div>
  </div>  

  <div class="row mt-4">
    <div class="col">
      
        <table class="table">
            <thead class="table-dark">
              <tr>
                <th scope="col">Title</th>
                <th scope="col">Created at</th>
                <th scope="col">Items</th>
                <th scope="col">Size</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for album in object_list %}
              <tr>
                <th><i class="fa-solid fa-folder-closed"></i>
                    <a href="{% url 'albums:detail' album.id %}">
                        {{ album.title }}</a>
                </th>
                <th>{{ album.created_at }}</th>
                <th>{{ album.images.count }}</th>
                <th>{{ album.size }} Mb </th>
              </tr>
              {% endfor %}

            </tbody>
          </table>

    </div>
  </div>
  

{% endblock %}